[project]
name = "2026-QuEra-Technical"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "bloqade-circuit[cirq, stim, tsim]>=0.11.0",
    "ipykernel>=7.1.0",
    "stimcirq>=1.15.0",
]